comment:                  
  layout: " diff, flags, files"
  behavior: default
  require_changes: false  
  require_base: false
  require_head: true  
ignore:
  - '**/*.g.dart'
  - '**/entities/'
  - 'lib/core/error/'
  - 'lib/core/usecases/'
  - 'lib/dependency_injection.dart'
  - 'lib/core/routes/'
