name: unsplash_sample
description: "A Flutter project to showcase the implementation of Flutter concepts such as Bloc pattern, Dependency Injection (DI), Code Coverage, Testing, Clean Architecture, Analytics using Mixpanl and Feature flagging using Unleash "
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.8.4
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  cached_network_image: ^3.3.0
  dartz: ^0.10.1
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_blurhash: ^0.7.0
  flutter_cache_manager: ^3.3.1
  flutter_dotenv: ^5.1.0
  flutter_staggered_grid_view: ^0.7.0
  get_it: ^7.6.2
  mixpanel_flutter: ^2.1.1
  mocktail: ^1.0.0
  stream_transform: ^2.1.0
  unleash_proxy_client_flutter: ^1.4.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.1
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.3
  file: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/core/.env
