name: main action
on:
 push:
    branches: [main]
 pull_request:
    branches: [main]
 workflow_dispatch:
jobs:
  flutter_tests:
    name: Drive tests
    runs-on: macos-latest
    steps:
    - name: Create .env file
      run: |
        cat > lib/core/env/.env <<EOF
        UNSPLASH_API_KEY = ""
        EOF
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with: 
       channel: master
    - run: flutter test
